apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-190221-9tau-service
spec:
  selector:
    app: enterprise-system-190221-9tau
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
